spring:
    application:
        name: store
    datasource:
        url: jdbc:mysql://localhost:3306/store_api
        username: root
        password: Amafreak#1
    hibernate:
        show_sql: true
    flyway:
        baseline-on-migrate: true   
        enabled: true
        url: jdbc:mysql://localhost:3306/store_api
        user: root
        password: Amafreak#1 


