spring:
    application:
        name: store
    datasource:
        url: jdbc:mysql://localhost:3306/store_api
        username: root
        password: Amafreak#1
    jpa:
        show-sql: true
    flyway:
        baseline-on-migrate: true   
        enabled: true
        url: jdbc:mysql://localhost:3306/store_api
        user: root
        password: Amafreak#1 
    jwt:
        secret: ${JWT_SECRET}
        accessTokenExpiriation: 7200 #2 hrs
        refreshTokenExpiriation: 604800 #7 days
stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

websiteUrl: https://localhost:4242
