spring:
    application:
        name: store

    jwt:
        secret: ${JWT_SECRET}
        accessTokenExpiriation: 7200 #2 hrs
        refreshTokenExpiriation: 604800 #7 days
    profiles:
        active: dev
stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

