spring:
    application:
        name: store
stripe:
    api:
        url: https://api.stripe.com
    enabled: true
    timeout: 5000
    supportedCurrencies: USD,EUR,GBP

mail:
    host: https://smtp.gmail.com
    port: 5761